######################################################################
# Automatically generated by qmake (2.01a) mar. 29. juil. 17:53:45 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Bouton.h Choix.h Fenetre.h Imprimer.h Solution.h
SOURCES += Bouton.cpp Choix.cpp Fenetre.cpp Imprimer.cpp main.cpp Solution.cpp
